### ISSUE TITLE
Admin and commentators

### ISSUE THREAD

**Issue by Masce** [tohalla/isla#54]
Can teacher see commentators usernames etc? Can he identify and block troublemakers or does he have to contact someone? Should there be a chance to see and identify the commentators or have a chance to block people(IP-address) or is just comment erasing enough? Should us be worried about bots, spammers, advertisers etc.?

**Comment by tohalla** [comment]
I decided against storing ip addresses of the commentators, since e.g. all the computers in schools network may share the same public ip address. However, in future versions the administrator will be able to set the course only available via password or to authenticated users). Blocking ip addresses should be left to the server administrator and not to the application itself.

I will close this issue, please reopen if necessary.
